version: "3"

services:
  sample:
    container_name: pet_front
    build:
      context: .
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true
    stdin_open: true
